name: Deploy API to Beanstalk
on:
  push:
    branches:
      - main
    paths:
      - 'Api/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Build Release
        run: |
          cd Api
          dotnet build --configuration Release

      - name: Publish .NET API
        run: |
          cd Api
          dotnet publish -c Release -o publish

      - name: Install EB CLI via pip
        run: |
          sudo apt-get update
          sudo apt-get install python-pip
          pip install awsebcli --upgrade

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Existing Environment
        run: |
          cd Api/publish
          eb init foodretail-application --region ${{ secrets.AWS_REGION }} -p "dotnetcore-8.0"
          eb deploy foodretail-env

      - name: Cleanup
        run: |
          rm -rf Api/publish
