name: Update .NET API on AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'API/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Build Release
        run: |
          cd API
          dotnet build --configuration Release

      - name: Publish .NET API
        run: |
          cd API
          dotnet publish -c Release -o publish

      - name: Install EB CLI
        run: |
          curl -sL https://s3.amazonaws.com/elasticbeanstalk-cli-resources/install-ebcli.sh | sudo bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Existing Environment
        run: |
          cd API/publish
          eb init foodretail-application --region us-west-2 -p "dotnetcore-8.0"
          eb deploy foodretail-env  # Deploy the new version to the existing environment

      - name: Cleanup
        run: |
          rm -rf API/publish
