name: Deploy API to Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'Api/**'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.*'
  AWS_REGION: 'eu-west-1'
  BUILD_ARTIFACT: "dotnet-app-${{ github.sha }}.zip"
  DEPLOY_PACKAGE_NAME: 'site.zip'

jobs:
  build_and_create_Artifact:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/out

      - name: Prepare Deployment Package
        run: |
          # Ensure aws-windows-deployment-manifest.json is in the output directory
          Copy-Item -Path ${{ github.workspace }}/Api/aws-windows-deployment-manifest.json -Destination ${{ github.workspace }}/out/
          cd ${{ github.workspace }}/out/
          # Compress all files including the manifest into the final deployment package
          Compress-Archive -Path * -DestinationPath ${{ github.workspace }}/${{ env.DEPLOY_PACKAGE_NAME }}
          # Verify the contents of the deployment package
          Expand-Archive -Path ${{ github.workspace }}/${{ env.DEPLOY_PACKAGE_NAME }} -DestinationPath ${{ github.workspace }}/verify/
          Get-ChildItem -Path ${{ github.workspace }}/verify/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Application_Artifact
          path: ${{ github.workspace }}/${{ env.DEPLOY_PACKAGE_NAME }}

  ServerDeployment:
    needs: build_and_create_Artifact
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Application_Artifact
          path: out

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: foodretail-application
          environment_name: test-env
          version_label: ${{ github.run_number }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: out/${{ env.DEPLOY_PACKAGE_NAME }}
          existing_bucket_name: elasticbeanstalk-eu-west-1-924511948270
